### ISSUE TITLE
PUSH not working with session serialization

### ISSUE THREAD

**Issue by mcollovati** [vaadin/azure-kit#10]
With Spring Session in action, Vaadin PUSH feature is not working.

When the Vaadin application is loaded, the PUSH connection is established, but then, since `AtmospherePushConnection` (the component responsible for bidirectional handling of messages between browser and server through `AtmosphereResource`) is part of the UI, it gets serialized and deserialized during every request.

The internal `AtmosphereResource` is transient, so it is null after deserialization, effectively preventing the communication with the browser. For this reason, `AtmospherePushConnection` also has a custom deserialization hook that always sets the internal state to `DISCONNECTED`.

When a message needs to be sent to the browser, `AtmospherePushConnection` results disconnected and moves itself into a `PENDING` state, without delivering the contents.

The transition from `PENDING` to `CONNECTED` happens only during the initial connection, but the channel is effectively already active, so Flow client will not attempt to reconnect.

This problem may also arise with different session serialization approaches.

**Comment by mcollovati** [comment]
Another problem with Spring Session (but perhaps also with other solutions that completely replace in memory HttpSession) is that the session should be serialized after sending or receiving PUSH messages.
This unfortunately is not working out of the box.
With long polling session serialization is executed when AtmosphereResource is suspendend, before we actually apply AtmospherePushConnection connection; furthermore, Spring Session filter is executed once per request, so even forcing it again will not serialize the session.
With websocket transport, Spring Session filter is executed only during handshake; trying to use it within an AtmosphereInterceptor also fails because Atmosphere request wrapper is missing a reference to the servlet context, used internally by Spring Filter.

**Comment by mcollovati** [comment]
Once/If session serialization issues are fixed, we may also investigate [Atmosphere configure for the Cloud](https://github.com/Atmosphere/atmosphere/wiki/Configuring-Atmosphere-for-the-Cloud)

There are OOB `ClusterBroadcastFilter` implementations for Redis and Hazelcast on [atmosphere-extensions repository](https://github.com/Atmosphere/atmosphere-extensions)

**Comment by mcollovati** [comment]
I did some experiment with a custom `AtmospherePushConnection` provided by a `PushConnectionFactory`. 
The custom `AtmospherePushConnection` holds a UUID, generated in the constructor, that is correctly serialized/deserialized and does never change.
This UUID is used to fetch the `AtmosphereResource` provided during connection from Atmosphere (`Universe.resourceFactory()`) during deserialization.

This works for websocket transport, but fails with long polling.
However, even if we re-attach the atmosphere resource, the UIDL `syncId` sometimes went out of sync, because VaadinSession is not serialized after push message is sent to the client

**Comment by mcollovati** [comment]
The wrong sync id can be caused by VaadinSession not serialized after pushing messages, or by operating on an "old" UI instance.
This may happen for example if we capture the UI in a background job to use 'UI.access'; when the job is executed the sync id may be older than the one of the latest deserialized instance

**Comment by mcollovati** [comment]
Using a full Websocket transport on Push seems to make the app more stable.
Needs more tests, especially when the backend node changes

**Comment by mcollovati** [comment]
With full websocket we acquire a reference to the session obtained during the handshake request, and then always work on that instance.
However, if we open a new browser tab, we will see that the count of UIs in VaadinSession for the requests of the first tab is still one, so it is not in sync with the current VaadinSession.

**Comment by heruan** [comment]
Closing this as solved by replacing Spring Session with our own approach.
