### ISSUE TITLE
Investigate using the Microstream library to facilitate session serialization

### ISSUE THREAD

**Issue by tamasmak** [vaadin/azure-kit#18]
The Microstream library:
https://docs.microstream.one/manual/intro/welcome.html
https://github.com/microstream-one/microstream

**Comment by tamasmak** [comment]
MicroStream is an object graph persistence engine built for the JVM. We can use it for storing Java object graphs and restoring them in memory.

- it has its own serialization [solution](https://stackoverflow.com/questions/58735841/how-does-microstream-deserialization-work/58835978#58835978) built from scratch, replacing Java serialization
- it supports all kind of Java types and [features](https://docs.microstream.one/manual/storage/addendum/supported-java-features.html)
- it handles circular references during the serialization
- the serialization solution is used by the storage and the cache but can be used [standalone](https://docs.microstream.one/manual/serializer/index.html) as well

The serialization has been tested with the standalone approach using the [microstream-persistence-binary](https://docs.microstream.one/manual/serializer/index.html#_prerequisites) dependency and this [implementation](https://docs.microstream.one/manual/serializer/index.html#_usage)

Findings:
- TODO

**Comment by heruan** [comment]
> As a result, until the lambda serialization is not solved properly we can't rely on this library.

Closing as per this limitation.
