### ISSUE TITLE
Document best practices for session replication

### ISSUE THREAD

**Issue by mcollovati** [vaadin/azure-kit#29]
To perform session replication, it is necessary that application code correctly implements Java Serialization.
We should document patterns and best practice to adopt, in the context of a Vaadin application.
Some points may be:

* implement Serializable whenever it is possible
* mark field as transient if they cannot be serializable (e.g. a component references a third party not Serializable class)
* don't capture not serializable objects in lambdas
* use of custom serialization hooks for complex cases (maybe just a sentence and a link to the Java documentation)

**Comment by heruan** [comment]
Done in https://github.com/vaadin/docs/pull/1867
